### ISSUE TITLE
ADB - Connection refused when device are ready for use

### ISSUE THREAD

**Issue by panarik** [DeviceFarmer/stf#161]
**Initial Conditions:**
Configurated ADB token by another machine in the same subnet

Case 1:
 - Step 1: click on device in UI inteface STF
 - Step 2: copy adb comand
 - Step 3: Run this comand on another machine on same subnet: `adb connect 192.168.1.70:7425`
 Result: `failed to authenticate to 192.168.1.70:7409`, device works: `192.168.1.70:7409       device`

Case 2:
 - Step 1: DO NOT click on device in UI inteface STF. Device are NOT beasy.
 - Step 2: ADB comand for this device on another machine on same subnet: `adb connect 192.168.1.70:7405`
 Result: `failed to connect to '192.168.1.70:7405': Connection refused`, device NOT works.

**Conclusion:**
Its normal, that Connection refused if device is ready for use on UI?

**ENV:**
Device: Redmi Note 4x
STF build by this docker-compose: https://github.com/DeviceFarmer/stf/blob/master/docker-compose.yaml
Changed only URL

**Comment by koral--** [comment]
ad 1.
It is a known (but not resolved yet) issue, existing since times of OpenSTF https://github.com/openstf/stf/issues/973 (linked issue is closed but actually it wasn't resolved).
It may look complicated but OpenSTF project is no longer maintained (so nobody has updated the issue status there) and in Device Farmer it is not yet fixed.

ad 2. It looks like intended behavior. If you don't reserve that device neither using API nor web UI you cannot connect to it.

**Comment by panarik** [comment]
Thank You for answer!
May You tell, where I can find API command for reserve device?

> ad 2. It looks like intended behavior. If you don't reserve that device neither using API nor web UI you cannot connect to it.
