### ISSUE TITLE
Links to dependencies

### ISSUE THREAD

**Issue by zlatsv** [DeviceFarmer/stf#46]
Ubuntu 18.04, STF 3.4.3
Pre-changed package placement prefix:
mkdir "${HOME}/.npm-packages"
npm config set prefix "${HOME}/.npm-packages"
Crashed at startup with no dependencies: stf-device-db, stf-browser-db, adbkit, adbkit-apkreader and other.
Temporarily fixed by doing:
cd ~/.npm-packages/lib/node_modules/@devicefarmer/stf/node_modules
for i in $(ls @devicefarmer/); do ln -s @devicefarmer/$i . ; done
Then crashed with no dependencies - minicap-prebuilt-beta, minitouch-prebuilt-beta. So I added:
cd ~
npm install -g minicap-prebuilt-beta minitouch-prebuilt-beta
cd ~/.npm-packages/lib/node_modules/@devicefarmer/stf/node_modules
ln -s ../../../minicap-prebuilt-beta .
ln -s ../../../minitouch-prebuilt-beta .

**Comment by koral--** [comment]
When do you get this error?
Are you trying to build from sources?

**Comment by zlatsv** [comment]
Following the instructions after installation (https://github.com/DeviceFarmer/stf#installation)
npm install -g @devicefarmer/stf
and start 
stf local --public-ip 10.10.11.71

**Comment by zlatsv** [comment]
![image](https://user-images.githubusercontent.com/33660583/88045246-0d108080-cb57-11ea-8fd1-7de6dad73831.png)

**Comment by koral--** [comment]
Sorry for the inconvenience.
At the time of writing this part of the instruction is not working as expected because version 3.4.3 is not yet published to npmjs.
We are in the middle of rebranding from OpenSTF to DeviceFarmer.

As a workaround you can either use docker image (latest tag) or build stf via `npm install`.
I'll keep this issue open until stf is installable from npmjs.

**Comment by koral--** [comment]
Version 3.4.3 has just been published to npmjs.
