### ISSUE TITLE
How can I configure minicap arguments?

### ISSUE THREAD

**Issue by ZhyliaievD** [DeviceFarmer/stf#557]
Hi, 
I use the latest devicefarmer/stf dockerhub image for a STF setup with providers distributed in different locations. While using from internal network performs well, colleagues who work from home have a very poor performance

I'm looking for a way to tune that. JPEG quality and frame rate looks like a right point to start from.

I wonder if there is a way to configure minicap arguments, e.g. frame rate argument `-r` ????(see https://github.com/openstf/minicap/pull/183/)

**Comment by denis99999** [comment]
@ZhyliaievD currently only some minicap arguments are configurable by the user, JPEG quality is one of them, I just added the frame rate argument through the PR #558, I hope that will help you! 
Moreover, in order to minimize the network traffic due to the screen cast, I recommend you to perform the following actions:
- Remove the screensaver
- Configure a fixed wallpaper, i.e. without movement
- Do not leave the screen moving unnecessarily, but rather return to the home screen

Regards.

**Comment by ZhyliaievD** [comment]
Thanks
