### ISSUE TITLE
Disable auto rollback

### ISSUE THREAD

**Issue by MaxLoooL** [DeviceFarmer/stf#57]
Hi team! Help solve the problem, please. When I press the "stop using" button, all the changes that I made during this session disappear: downloading applications, updating them, and so on. Have you encountered this?

**Comment by denis99999** [comment]
@MaxLoooL ,
You can launch STF with the `--no-cleanup` parameter

**Comment by MaxLoooL** [comment]
> @MaxLoooL ,
> You can launch STF with the `--no-cleanup` parameter

This option did not solve the problem. I will try to describe the sequence of actions:
1. I go to the controller, choose the device I need
2. For example, I download an application from Google Play and configure
3. I complete all the settings, press the button to stop using
After that, on my device, all applications are closed, and all changes in the previous session are rolled back.
There is one more side to the problem:
1. I do all application settings right on the device
2. After that I go to the controller, check if everything is working and click "stop using"
In this case, all actions are rolled back.
Have you encountered this?
P.S. If this is important, the device has root rights

**Comment by MaxLoooL** [comment]
Hi, team! Any updates for this question? @koral-- @denis99999

**Comment by koral--** [comment]
I don't quite understand what is the issue.
What exactly do you want to achieve?
Do you observe different behavior with and without `--no-cleanup` flag?

**Comment by denis99999** [comment]
@MaxLoooL,

Please fill the issue template because I don't meet this problem: I enabled `--no-cleanup` flag and when I download an application and I configure it, then updates are not rolled back after clicking on "Stop Using" button.

Do you meet the same issue with all devices (rooted or not) ?

You can also enable the `--screen-reset` flag (i.e. set to `false `value) to keep your screen as it was before closing the session.

**Comment by MaxLoooL** [comment]
Thanks a lot! Now it's worked!
