### ISSUE TITLE
Automatically removed the app when finished

### ISSUE THREAD

**Issue by tuyenlq** [DeviceFarmer/stf#576]
Hi ,
I was install app via upload apk file on web but i stopped using app automatically removed, how to keep the app ?
Thanks

**Comment by jupe** [comment]
stf removes all apps that is installed during session, no way to keep them at the moment since it's designed so. See https://github.com/DeviceFarmer/stf/blob/da6c786a51181857be738c012147b9f6c8fe5a1c/lib/units/device/plugins/cleanup.js#L40 . If you install apps manually before stf sessions it should keep them untouched. Does that work for you ?

**Comment by tuyenlq** [comment]
Thanks @jupe
